### ISSUE TITLE
Can't use the API at all, host is probs not on..

### ISSUE THREAD

**Issue by TparT** [anish-shanbhag/minecraft-api#6]
When trying to use the API (even after waiting about a minute after the first request) it just responds with an error saying: 'DNS_PROBE_FINISHED_NXDOMAIN'
Which is basically an error saying 'No address associated with hostname' meaning the API's host is not on or there is another issue..

I have tried with most of the endpoints including the ones in the examples.

Would really love to use this API for my app :)

**Comment by anish-shanbhag** [comment]
Sorry I've ignored this for so long. I know it's been absolutely forever, but the API should be working again now :)

I've moved the hosting over to Vercel, so the API going down theoretically shouldn't ever be a problem again (it was down before because my AWS credits expired). The docs and readme should both be updated with all the new endpoint info.
